"use strict";
/* UPSC ZONE AI — study-youtube.js
   Features: #139 #140 #141 #142 #143 #144 #145 #146 #147 #148 #149 #150 #151 #152 #233
   YtAPI isolated & API-ready. Simulated platform — no real embeds. */
const LS = "uza_youtube_v1";
const $ = s => document.querySelector(s);
const wait = ms => new Promise(r => setTimeout(r, ms));
const esc = s => { const d = document.createElement("div"); d.textContent = s; return d.innerHTML; };
let S = {}; try { S = JSON.parse(localStorage.getItem(LS)) || {}; } catch {}
S.channels = S.channels || { "UPSC Pathshala": true, "Sleepless IAS": true, "Polity Simplified": true, "Vlog Nation": false };
S.watchToday = S.watchDay === new Date().toDateString() ? (S.watchToday || 0) : 0;
S.watchDay = new Date().toDateString();
const save = () => { S.watchDay = new Date().toDateString(); localStorage.setItem(LS, JSON.stringify(S)); };
function toast(m) { const t = $("#toast"); t.textContent = m; t.hidden = false; clearTimeout(toast._t); toast._t = setTimeout(() => t.hidden = true, 2800); }

const VIDEOS = [
  { id: "v1", title: "Indian Monsoon mechanism in 12 minutes", ch: "UPSC Pathshala", dur: 720, topic: "monsoon geography", thumb: "t1", kw: ["monsoon", "geography", "itcz"] },
  { id: "v2", title: "Article 32 vs 226 — writs without confusion", ch: "Polity Simplified", dur: 640, topic: "polity writs", thumb: "t2", kw: ["polity", "writs", "article 32"] },
  { id: "v3", title: "MPC & repo rate — economy crash course", ch: "Sleepless IAS", dur: 900, topic: "economy monetary", thumb: "t3", kw: ["economy", "repo", "mpc"] },
  { id: "v4", title: "One Nation One Election — federalism debate", ch: "UPSC Pathshala", dur: 830, topic: "polity elections", thumb: "t1", kw: ["election", "federalism"] },
  { id: "v5", title: "Laxmikanth Ch. 8 in 15 minutes", ch: "Polity Simplified", dur: 910, topic: "polity parliament", thumb: "t2", kw: ["polity", "parliament", "laxmikanth"] },
  { id: "v6", title: "5-minute 'study motivation' short", ch: "Vlog Nation", dur: 45, topic: "shorts", thumb: "t3", kw: ["motivation", "short"], type: "short" },
  { id: "v7", title: "Top 10 movie trailers of the week", ch: "Vlog Nation", dur: 540, topic: "entertainment", thumb: "t1", kw: ["movie", "trailer"], type: "ent" },
  { id: "v8", title: "ENSO, IOD and monsoon forecasts explained", ch: "Sleepless IAS", dur: 760, topic: "geography climate", thumb: "t3", kw: ["monsoon", "el nino", "climate"] }
];
const DISTRACT_WORDS = ["movie", "song", "game", "trailer", "comedy", "roast", "vlog life"];
let playing = null, playTimer = null, playedSec = 0, blockAttempts = 0;

const YtAPI = {
  async transform(kind, v) {           // #144–#148
    await wait(850);
    return {
      summary: `“${v.title}” distils ${v.topic} into exam-ready anchors: definition, one PYQ frame, one current hook. Watch-value: high for ${v.kw[0]}. (#144)`,
      notes: `${v.title} — video notes\nChannel: ${v.ch} (${S.channels[v.ch] ? "whitelisted" : "not whitelisted"})\n\n• Core: ${v.topic}\n• Anchors: ${v.kw.join(", ")}\n• Use in: GS answer introductions.\n\nGenerated by Study-Only YouTube (#145).`,
      mcqs: [{ q: `From “${v.title}”, the anchor most likely tested is:`, o: [v.kw[0], "Unrelated trivia", "None", "All"], a: 0 }],
      cards: [{ f: `Key idea from ${v.ch}'s ${v.kw[0]} video?`, b: `The video anchors ${v.topic} for ${v.kw[0]}-framed questions.` }],
      map: [`Central: ${v.title}`, ...v.kw.map(k => `→ ${k}`), "→ PYQ", "→ Revision queue"]
    }[kind];
  }
};

/* ---------- watch time (#149) ---------- */
function watchUI() { $("#watch-total").textContent = `⏱ ${Math.floor(S.watchToday / 60)}m today`; }

/* ---------- render library ---------- */
function renderVids(q = "") {
  const list = VIDEOS.filter(v => (v.title + " " + v.kw.join(" ") + " " + v.ch).toLowerCase().includes(q.toLowerCase()));
  const grid = $("#vid-grid");
  if (!list.length) { grid.innerHTML = `<div class="empty" style="grid-column:1/-1">No UPSC videos match — try monsoon, polity, economy.</div>`; return; }
  grid.innerHTML = list.map(v => {
    const blocked = (v.type === "short" && $("#block-shorts").checked) || (v.type === "ent" && $("#block-ent").checked);
    return `<article class="vid">
      <div class="thumb ${v.thumb}" aria-hidden="true">▶<span class="dur">${Math.floor(v.dur / 60)}:${String(v.dur % 60).padStart(2, "0")}</span></div>
      <div class="vid-body"><h3>${esc(v.title)}</h3>
        <div class="vid-meta"><span class="ch-chip ${S.channels[v.ch] ? "" : "off"}">${esc(v.ch)}</span>${blocked ? '<span class="ch-chip off">blocked</span>' : ""}</div>
        <div class="vid-actions"><button class="btn btn-dark btn-sm" data-play="${v.id}" type="button" ${blocked ? "" : ""}>${blocked ? "⛔ Blocked" : "▶ Study this"}</button></div>
      </div></article>`;
  }).join("");
  grid.querySelectorAll("[data-play]").forEach(b => b.addEventListener("click", () => {
    const v = VIDEOS.find(x => x.id === b.dataset.play);
    const blocked = (v.type === "short" && $("#block-shorts").checked) || (v.type === "ent" && $("#block-ent").checked);
    if (blocked) {
      blockAttempts++;
      $("#banner-out").innerHTML = `<div class="block-banner">⛔ <strong>${v.type === "short" ? "Shorts are blocked (#150)." : "Entertainment video blocked (#151)."}</strong>
        Study-Only YouTube keeps the feed clean. Distraction attempts logged: ${blockAttempts}.</div>`;
      if (blockAttempts >= 2) {
        $("#banner-out").insertAdjacentHTML("beforeend", `<div class="nudge" style="margin-top:9px">🧭 <strong>Distraction pattern detected (#152):</strong> ${blockAttempts} blocked attempts in this session. The AI suggests a 5-minute revision sprint instead — <a href="revision.html" style="color:inherit;font-weight:800">open Revision Center</a>.</div>`);
      }
      toast("Blocked by the study filter.");
      return;
    }
    play(v);
  }));
}

/* ---------- player + watch tracking ---------- */
function play(v) {
  playing = v; playedSec = 0;
  clearInterval(playTimer);
  $("#player-card").hidden = false;
  renderPlayer();
  $("#player-card").scrollIntoView({ behavior: "smooth", block: "center" });
}
function renderPlayer() {
  const v = playing;
  $("#player").innerHTML = `<div class="player-screen">
    <h3>${esc(v.title)}</h3><p class="muted">${esc(v.ch)} · whitelisted study channel</p>
    <div class="pbar"><span id="pfill" style="width:${playedSec / v.dur * 100}%"></span></div>
    <div class="player-ctrl">
      <button class="btn btn-primary btn-sm" id="p-toggle" type="button">⏸ Pause</button>
      <span class="muted small" id="p-time">0:00 / ${Math.floor(v.dur / 60)}:${String(v.dur % 60).padStart(2, "0")}</span>
      <span class="muted small">watch tracking ON (#149)</span></div></div>
    <div class="transform-row">
      <button class="btn btn-ghost btn-sm" data-tf="summary" type="button">📄 Summary (#144)</button>
      <button class="btn btn-ghost btn-sm" data-tf="notes" type="button">📝 Notes (#145)</button>
      <button class="btn btn-ghost btn-sm" data-tf="mcqs" type="button">🧩 MCQs (#146)</button>
      <button class="btn btn-ghost btn-sm" data-tf="cards" type="button">🃏 Flashcards (#147)</button>
      <button class="btn btn-ghost btn-sm" data-tf="map" type="button">🗺 Mind Map (#148)</button></div>`;
  startTicker(true);
  $("#p-toggle").addEventListener("click", () => {
    const running = startTicker(null);
    $("#p-toggle").textContent = running ? "⏸ Pause" : "▶ Resume";
  });
  $("#player").querySelectorAll("[data-tf]").forEach(b => b.addEventListener("click", async () => {
    const out = $("#tf-out");
    out.innerHTML = `<div class="tool-box"><span class="spinner"></span> AI transforming this video…</div>`;
    const r = await YtAPI.transform(b.dataset.tf, v);
    if (b.dataset.tf === "notes") {
      const store = JSON.parse(localStorage.getItem("uza_ca_notes_v1") || "[]"); store.push({ t: new Date().toISOString(), text: r });
      localStorage.setItem("uza_ca_notes_v1", JSON.stringify(store));
      out.innerHTML = `<div class="tool-box"><strong>Notes saved to Smart Notes bridge ✓</strong><pre style="white-space:pre-wrap;font-family:var(--fb);font-size:.8rem;margin-top:6px">${esc(r)}</pre></div>`;
    } else if (b.dataset.tf === "mcqs") {
      out.innerHTML = `<div class="tool-box"><strong>MCQs from video (#146)</strong><ul>${r.map(q => `<li>${esc(q.q)} <em>(answer: option ${q.a + 1})</em></li>`).join("")}</ul></div>`;
    } else if (b.dataset.tf === "cards") {
      out.innerHTML = `<div class="tool-box"><strong>Flashcards (#147)</strong><ul>${r.map(c => `<li><strong>${esc(c.f)}</strong> — ${esc(c.b)}</li>`).join("")}</ul></div>`;
    } else if (b.dataset.tf === "map") {
      out.innerHTML = `<div class="tool-box"><strong>Mind map (#148)</strong><ul>${r.map(x => `<li>${esc(x)}</li>`).join("")}</ul></div>`;
    } else out.innerHTML = `<div class="tool-box"><strong>Video summary (#144)</strong><p style="margin-top:6px">${esc(r)}</p></div>`;
  }));
}
let running = true;
function startTicker(force) {
  if (force != null) running = force;
  clearInterval(playTimer);
  if (!running) return false;
  playTimer = setInterval(() => {
    playedSec += 5; S.watchToday += 5; save(); watchUI();
    const v = playing;
    $("#pfill").style.width = Math.min(100, playedSec / v.dur * 100) + "%";
    $("#p-time").textContent = `${Math.floor(playedSec / 60)}:${String(playedSec % 60).padStart(2, "0")} / ${Math.floor(v.dur / 60)}:${String(v.dur % 60).padStart(2, "0")}`;
    if (playedSec >= v.dur) { clearInterval(playTimer); toast("Video complete — logged to watch analytics (#149) ✓"); }
  }, 5000); // demo speed: 5s of video per real second
  return true;
}

/* ---------- search + content filter (#233 #140 #141) ---------- */
$("#vy-form").addEventListener("submit", e => {
  e.preventDefault();
  const q = $("#vy-q").value.trim().toLowerCase();
  if (DISTRACT_WORDS.some(d => q.includes(d))) {
    $("#banner-out").innerHTML = `<div class="block-banner">⛔ <strong>AI Video Content Filter (#141):</strong> “${esc(q)}” isn't UPSC study content. The query was blocked at the gate — try monsoon, polity, economy.</div>`;
    renderVids("");
    return;
  }
  $("#banner-out").innerHTML = "";
  renderVids(q);
});

/* ---------- toggles ---------- */
$("#block-shorts").addEventListener("change", () => { save(); renderVids($("#vy-q").value.trim().toLowerCase()); });
$("#block-ent").addEventListener("change", () => { save(); renderVids($("#vy-q").value.trim().toLowerCase()); });

/* ---------- channel whitelist (#143) ---------- */
$("#chan-btn").addEventListener("click", () => {
  $("#mgmt-out").innerHTML = `<div class="mgmt"><strong>Study Channel Whitelist <span class="fid">#143</span></strong>
    ${Object.entries(S.channels).map(([c, on]) => `<div class="list-row"><span>${esc(c)} ${on ? "🟢" : "⛔"}</span>
      <button class="btn btn-ghost btn-sm" data-ch="${esc(c)}" type="button">${on ? "Remove" : "Allow"}</button></div>`).join("")}
    <p class="muted small" style="margin-top:8px">Only whitelisted channels appear in recommendations (#142).</p></div>`;
  $("#mgmt-out").querySelectorAll("[data-ch]").forEach(b => b.addEventListener("click", () => {
    S.channels[b.dataset.ch] = !S.channels[b.dataset.ch]; save();
    $("#chan-btn").click(); renderVids($("#vy-q").value.trim().toLowerCase()); renderReco();
    toast(S.channels[b.dataset.ch] ? "Channel allowed ✓" : "Channel removed from whitelist.");
  }));
});

/* ---------- recommendations (#142) ---------- */
function renderReco() {
  const reco = VIDEOS.filter(v => !v.type && S.channels[v.ch]).slice(0, 4);
  $("#reco-strip").innerHTML = reco.map(v => `<article class="vid">
    <div class="thumb ${v.thumb}" aria-hidden="true">▶<span class="dur">${Math.floor(v.dur / 60)}m</span></div>
    <div class="vid-body"><h3>${esc(v.title)}</h3>
      <div class="vid-actions"><button class="btn btn-dark btn-sm" data-reco="${v.id}" type="button">▶ Play</button></div></div></article>`).join("");
  $("#reco-strip").querySelectorAll("[data-reco]").forEach(b => b.addEventListener("click", () => play(VIDEOS.find(v => v.id === b.dataset.reco))));
}

document.addEventListener("DOMContentLoaded", () => { watchUI(); renderVids(); renderReco(); });
